language: haskell

# We don't have any actual tests.
# However building this across different
# package versions is hard, so that's really
# what we're interested in.

# We've set up GHC 7.4 to look similar to
# debain wheezy and GHC 7.6 to look similar
# to debian jessie.

# Long-term I should probably switch over
# to release of the Haskell Platform to test
# against - the debain-based approach skips
# QuickCheck version 2.6.

matrix:
  include:
    - ghc: 7.4.1
      env: CONFIG=platform/2012.2.0.0

    - ghc: 7.4.2
      env: CONFIG=platform/2012.4.0.0

    - ghc: 7.6
      env: CONFIG=platform/2013.2.0.0

    - ghc: 7.8.4
      env: CONFIG=platform/2014.2.0.0

    - ghc: 7.4
      env: CONFIG=debian/wheezy

    - ghc: 7.8

install:
 - if ! [[ -z "$CONFIG" ]]; then
     curl "https://raw.githubusercontent.com/aslatter/haskell-constraints/master/$CONFIG/cabal.config" > cabal.config;
   fi
 - cabal install --dependencies-only

# We don't need sudo
sudo: false

